In [14]:
#creating a new pandas library
# These three commands i have to do in the terminal
# git add .
# git commit -m "added a new pandas library"
# git push origin main

In [15]:
import numpy as np

In [16]:
arr1=np.array([1,2,3,4,5])  

In [17]:
type(arr1)

numpy.ndarray

In [18]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [19]:
# metoh 2 

In [20]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
arr4=np.ones((1,3))
arr4

array([[1., 1., 1.]])

In [22]:
arr5=np.identity(3)
arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:

arr7 = np.eye(3, 4, k=2)
print(arr7)

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [24]:
arr6=np.arange(1,10,2)
arr6

array([1, 3, 5, 7, 9])

In [25]:
arr7=np.linspace(1,10,10)
"""
This code snippet demonstrates the use of the numpy function `linspace`.

`np.linspace(start, stop, num)` returns `num` evenly spaced samples, calculated over the interval `[start, stop]`.

In this example:
- `start` is 1
- `stop` is 10
- `num` is 5

The resulting array `arr7` will contain 5 evenly spaced values between 1 and 10.
"""
arr7 
# in the 

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
arr8=np.copy(arr7)
arr8

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [27]:
# Numpy Properties & Attributes
#1. Shape
#2. nDim
#3. Size
#4. Itemsize
#5. astype()

In [32]:
#shape
print(arr7.shape)



(3, 4)
