In [1]:
#creating a new pandas library


In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5])  

In [3]:
type(arr1)

numpy.ndarray

In [ ]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
# metoh 2 

In [5]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
arr5=np.identity(3)
arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
arr6=np.eye(3)
arr6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
arr6=np.arange(1,10,2)
arr6

array([1, 3, 5, 7, 9])