In [14]:
#creating a new pandas library
# These three commands i have to do in the terminal
# git add .
# git commit -m "added a new pandas library"
# git push origin main

In [15]:
import numpy as np

In [16]:
arr1=np.array([1,2,3,4,5])  

In [17]:
type(arr1)

numpy.ndarray

In [18]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [19]:
# metoh 2 

In [20]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
arr4=np.ones((1,3))
arr4

array([[1., 1., 1.]])

In [22]:
arr5=np.identity(3)
arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:

arr7 = np.eye(3, 4, k=2)
print(arr7)

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [24]:
arr6=np.arange(1,10,2)
arr6

array([1, 3, 5, 7, 9])

In [25]:
arr7=np.linspace(1,10,10)
"""
This code snippet demonstrates the use of the numpy function `linspace`.

`np.linspace(start, stop, num)` returns `num` evenly spaced samples, calculated over the interval `[start, stop]`.

In this example:
- `start` is 1
- `stop` is 10
- `num` is 5

The resulting array `arr7` will contain 5 evenly spaced values between 1 and 10.
"""
arr7 
# in the 

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
arr8=np.copy(arr7)
arr8

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [27]:
# Numpy Properties & Attributes
#1. Shape
#2. nDim
#3. Size
#4. Itemsize
#5. astype()

In [32]:
#shape
print(arr7.shape)



(3, 4)


In [40]:
arr9= np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[5,6],[7,8]]])
print(arr9.shape)

(3, 2, 2)


In [41]:
arr1.ndim # it is not a funciton it is a atribute 

1

In [42]:
arr1.size # no of elemts present in the array

5

In [43]:
arr9.itemsize  # size of each element in the array  meanse the data type of the elemt int or float 

4

In [44]:
arr8.dtype # data type of the array  in what form is the data is 

dtype('float64')

In [45]:
arr9.astype('int')  # it will convert the data type of the array

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[5, 6],
        [7, 8]]])

In [ ]:
# Numpy vs list
#1. Less memory
#2. Fast
#3. Convenient


In [52]:
import sys
import time 
lista=range(100)
arr11=np.arange(100)

print(sys.getsizeof(5)*len(lista))
print(arr11.itemsize*arr11.size)
# this show that we should use array instead of list
x= range(10000000)
y=range(10000000,20000000)
start=time.time()
c=[x+y for x,y in zip(x,y)]
print("time taken by list",time.time()-start)
a=np.arange(10000000)
b=np.arange(10000000,20000000)
start=time.time()
c=a+b
print("time taken by array",time.time()-start)



2800
400
time taken by list 1.3675639629364014
time taken by array 0.19261550903320312


In [62]:
# reshape()
arr12=np.arange(24).reshape(6,4)


In [63]:
# Indexing ,Sclicing and Iterating
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [64]:
arr12[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [ ]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
arr1+arr2
arr1-arr2
arr1*arr2


In [65]:
arr2>4

array([[False, False, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [66]:
arr3=np.arange(6).reshape(2,3)
arr4=np.arange(6,12).reshape(3,2)

In [67]:
arr3.dot(arr4) # dot product of two arrays
print(arr4)

[[ 6  7]
 [ 8  9]
 [10 11]]


In [69]:
arr4.max()
arr4.min()

6

In [71]:
print(arr4)
arr4.min(axis=0)  # min of each column

[[ 6  7]
 [ 8  9]
 [10 11]]


array([6, 7])

In [ ]:
print(arr4)
arr4.min(axis=1)  # min of each row
arr4.mean(axis=0)  # mean of each column
arr4.sum(axis=1)  # sum of each row
arr4.std()  # standard deviation of the array


In [ ]:
print(np.median(arr4))  # median of the array
print(np.percentile(arr4, 25))  # 25th percentile of the array
print(np.exp(arr4))  # exponential of the array
print(np.log(arr4))  # log of the array
print(np.log10(arr4))  # log base 10 of the array
print(np.sin(arr4))  # sin of the array
print(np.cos(arr4))  # cos of the array
print(np.tan(arr4))  # tan of the array
print(np.tan(arr4))  # tan of the array

In [ ]:
# Reshapeing Numpy Array
# 1.Ravel()
# 2.Reshape()
# 3.Transpose()
# 4.Stacking()
# 5 spliting()





In [73]:
arr4.ravel()  # it will convert the 2d array into 1d array

array([ 6,  7,  8,  9, 10, 11])

In [74]:
arr4.transpose() # it will convert the row into column and column into row

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [75]:
arr5=np.arange(12,18).reshape(2,3)
np.hstack((arr3,arr5))  # it will stack the two array horizontally

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [76]:
np.vstack((arr3,arr5))  # it will stack the two array vertically

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
np.hsplit(arr3,3)  # it will split the array into 3 equal parts horizontal
np.vsplit(arr3,2)  # it will split the array into 2 equal parts vertically

[array([[0, 1, 2]]), array([[3, 4, 5]])]

In [80]:
arr8=np.arange(24).reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])